name: Build Transpire Module

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Run ID of the triggering workflow
      module_name:
        description: Name of transpire module to build
        required: false
        type: string

permissions:
  packages: write

run-name: build ${{ inputs.module_name }} (${{ inputs.run_id }})

jobs:
  module-ci:
    if: ${{ inputs.module_name != '' }}
    uses: ocf/transpire/.github/workflows/module-ci.yml@main
    with:
      module_name: ${{ inputs.module_name }}
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      OCF_CLUSTER_DEPLOY_KEY: ${{ secrets.OCF_CLUSTER_DEPLOY_KEY }}

  cluster-ci:
    if: ${{ inputs.module_name == '' }}
    uses: ocf/transpire/.github/workflows/cluster-ci.yml@main
    secrets:
      OCF_CLUSTER_DEPLOY_KEY: ${{ secrets.OCF_CLUSTER_DEPLOY_KEY }}
