name: Build Transpire Module

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: Run ID of the triggering workflow
      module-name:
        description: Name of transpire module to build
        required: true
        type: string

run-name: build ${{ inputs.module-name }} (${{ inputs.run-id }})

jobs:
  transpire-ci:
    uses: ocf/transpire/.github/workflows/module-ci.yml@main
    with:
      module-name: ${{ inputs.module-name }}
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
