name: Transpire Module CI

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
    secrets:
      TRANSPIRE_CI_PAT:
        required: true

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run CI
        run: python ./.github/workflows/trigger.py
        env:
          RUN_ID: ${{ github.run_id }}
          MODULE_NAME: ${{ inputs.module_name }}
          GITHUB_TOKEN: ${{ secrets.TRANSPIRE_CI_PAT }}
