name: Transpire Module CI

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ocf
          repo: transpire-ci
          workflow_id: build-module.yml
          inputs: '{"module-name": "${{ inputs.module-name }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
